sudo: required
services:
    - docker
before_install:
    - docker build -t 288880097/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true 288880097/react-test npm test

after_success:
    - docker build -t 288880097/multi-client ./client
    - docker build -t 288880097/multi-nginx ./nginx
    - docker build -t 288880097/multi-server ./server
    - docker build -t 288880097/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those image to docker hub
    - docker push 288880097/multi-client
    - docker push 288880097/multi-nginx
    - docker push 288880097/multi-server
    - docker push 288880097/multi-worker